replicaCount: 2

image:
  repository: loadinggreg/fiapx-user-management
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  nodePort: 30080

mysql:
  database: springdb
  user: springuser
  host: localhost
  port: 3306